PROC LOGISTIC
   DATA=&EM_IMPORT_DATA
   NAMELEN=200
   ;
   CLASS N_BRANCH  (PARAM=REF REF="377");
   MODEL  DEFAULT (EVENT='1') =  N_BRANCH
        /
   ITPRINT
   TECH=NEWTON
   MAXITER=1000
   ;
   ODS OUTPUT
   		FITSTATISTICS=N_BRANCH_FS;
RUN;
