PROC CONTENTS
           	DATA=&EM_IMPORT_DATA
           	OUT=VARIABLES_NAMES
			NOPRINT;
RUN;
 
PROC SQL ;
 
     SELECT
     DISTINCT NAME
	INTO
	:GROUP_VARIABLES SEPARATED BY " "
     FROM VARIABLES_NAMES
     WHERE NAME LIKE "GRP_%"
     ;
QUIT;
 
%LET VARLIST=&GROUP_VARIABLES.;
 
%LET VARLIST=%ENQUOTE(&VARLIST,SEPARATOR=);
%METADATA(NEWROLE=REJECTED,WHERE=(NAME IN (&VARLIST) AND UPCASE(ROLE)='INPUT'));
 
 